"""The ``shadowgate`` command-line interface.

Every subcommand is a ``_cmd_<name>(args) -> int`` function; :func:`main` parses arguments,
sets up logging and console encoding, dispatches, and turns errors into one-line messages and
exit codes (see :data:`EXIT_CODES`). Library modules never print; all output lives here.
"""

from __future__ import annotations

import argparse
import contextlib
import dataclasses
import datetime as _dt
import json
import logging
import math
import os
import sys
import textwrap
import time
import tomllib
import traceback
from collections.abc import Callable, Mapping, Sequence
from pathlib import Path
from typing import TYPE_CHECKING, Any

from . import __version__
from .errors import ConfigError, DatasetError, ShadowgateError

if TYPE_CHECKING:
    from .audit import AuditSummary
    from .config import Config
    from .ledger import Ledger
    from .runner import RunStats
    from .stats import Estimate
    from .sweep import OperatingPoint, SweepResult
    from .types import Decision

__all__ = ["main", "EXIT_CODES", "DEMO_CONFIG", "STARTER_CONFIG"]

log = logging.getLogger("shadowgate.cli")

EXIT_OK = 0
EXIT_RUNTIME = 1
EXIT_USAGE = 2
EXIT_BREACH = 3
EXIT_BUDGET = 4
EXIT_INTERRUPTED = 130

EXIT_CODES: dict[int, str] = {
    EXIT_OK: "success",
    EXIT_RUNTIME: "runtime error, or a run stopped after repeated failures",
    EXIT_USAGE: "usage or configuration error (bad arguments, config, task file, missing ledger)",
    EXIT_BREACH: "audit breach with --fail-on-breach",
    EXIT_BUDGET: "a run stopped because it reached its spending cap",
    EXIT_INTERRUPTED: "interrupted (Ctrl-C); completed work is in the ledger",
}

DEFAULT_LEDGER = Path(".shadowgate") / "ledger.sqlite"


class UsageError(ShadowgateError):
    """A command-line usage problem (exit code 2)."""


# --------------------------------------------------------------------------- templates

# Kept identical in content to examples/simulated.toml (a test checks this).
DEMO_CONFIG = """\
# Fully offline cascade over simulated models: no network, no API keys, deterministic.
# Generated by `shadowgate demo`. Re-run it with:
#
#   shadowgate run -c shadowgate.toml -t tasks.jsonl --ledger ledger.sqlite
#
# A simulated model answers task i correctly with probability sigmoid(skill - difficulty_i),
# where difficulty comes from each task's meta.difficulty (the built-in arithmetic generator
# uses roughly 2-17). Its verbal confidence tracks that probability plus `overconfidence`
# and noise, so the fast tier below is a cheap, clearly overconfident model.

[run]
name = "simulated-demo"
workers = 4
seed = 0
cache = false

[backends.fast]
type = "simulated"
skill = 8.5              # solves easy and medium problems, struggles with long ones
overconfidence = 0.35    # reports ~0.35 more confidence than its accuracy warrants
discrimination = 0.4     # right answers still score higher than wrong ones
confidence_noise = 0.03
pricing = { input = 0.10, output = 0.50 }      # USD per million tokens

[backends.slow]
type = "simulated"
skill = 24.0             # much stronger (near-perfect here), much more expensive
overconfidence = 0.0
pricing = { input = 4.00, output = 20.00 }

[[tiers]]
name = "fast"
backend = "fast"
threshold = 0.55                    # too permissive for this model: the audit shows it
confidence = { type = "verbal" }    # the model ends with "CONFIDENCE: <0-1>"

[[tiers]]
name = "slow"
backend = "slow"                    # final tier: always serves, no threshold

[answer]
extractor = "final_line"            # text after the last "ANSWER:"
comparator = { type = "numeric" }   # 1,000 == 1000.0

[audit]
mode = "inline"
rate = 0.2               # audit 20% of accepted cases outside the strata below
floor = 0.05
# [lo, hi, rate] on the fast tier's confidence: audit borderline acceptances more often.
strata = [[0.55, 0.9, 0.6], [0.9, 1.0, 0.3]]
tolerance = 0.05         # acceptable disagreement rate on skipped cases
"""

STARTER_CONFIG = """\
# shadowgate starter config: a two-tier cascade with shadow audits.
#
# As written it uses simulated models, so it runs offline with no API keys:
#
#   shadowgate run -c shadowgate.toml -t tasks.jsonl            # route the tasks
#   shadowgate audit                                           # how often is the fast tier wrong?
#   shadowgate run -c shadowgate.toml -t tasks.jsonl --mode eval
#   shadowgate sweep                                           # which threshold to use?
#   shadowgate report -o report.html
#
# To use real models, replace the two [backends.*] tables, for example:
#
#   [backends.fast]
#   type = "anthropic"                 # pip install "shadowgate[anthropic]"
#   model = "claude-haiku-5-5"
#   api_key_env = "ANTHROPIC_API_KEY"  # keys are read from the environment, never from here
#
#   [backends.slow]
#   type = "openai"                    # any OpenAI-compatible endpoint (OpenAI, vLLM, Ollama...)
#   model = "gpt-5"
#   base_url = "https://api.openai.com/v1"
#   api_key_env = "OPENAI_API_KEY"
#
# Other backend types: "claude-code" (the `claude` CLI), "command" (any shell command),
# "replay" (recorded completions) and "simulated".

[run]
name = "starter"
workers = 4
seed = 0
# max_cost_usd = 2.00      # stop submitting new tasks once spend reaches this
# cache = true             # reuse identical responses across runs
# ledger = ".shadowgate/ledger.sqlite"

[backends.fast]
type = "simulated"         # offline stand-in for a small, cheap model
skill = 8.0
overconfidence = 0.1
pricing = { input = 0.10, output = 0.50 }   # USD per million tokens

[backends.slow]
type = "simulated"         # offline stand-in for a large, expensive model
skill = 16.0
pricing = { input = 4.00, output = 20.00 }

[[tiers]]
name = "fast"
backend = "fast"
threshold = 0.8                     # serve when confidence >= 0.8, otherwise escalate
confidence = { type = "verbal" }    # the model ends its reply with "CONFIDENCE: <0-1>"

[[tiers]]
name = "slow"
backend = "slow"                    # the final tier always serves

[answer]
extractor = "final_line"            # text after the last "ANSWER:"
comparator = { type = "numeric" }

[audit]
mode = "inline"          # "deferred" records audits as pending for `shadowgate audit --run-pending`
rate = 0.2               # share of accepted (skipped) cases re-answered by the final tier
floor = 0.05
tolerance = 0.05         # acceptable disagreement rate on skipped cases
"""


# --------------------------------------------------------------------------- output helpers


def _out(text: str = "") -> None:
    print(text, file=sys.stdout)


def _err(text: str) -> None:
    print(text, file=sys.stderr)


def _jsonable(obj: Any) -> Any:
    """Convert dataclasses / paths / tuples to strict-JSON-compatible values (NaN/inf -> None)."""
    if dataclasses.is_dataclass(obj) and not isinstance(obj, type):
        return {f.name: _jsonable(getattr(obj, f.name)) for f in dataclasses.fields(obj)}
    if isinstance(obj, float):
        return obj if math.isfinite(obj) else None
    if isinstance(obj, (str, int, bool)) or obj is None:
        return obj
    if isinstance(obj, Path):
        return str(obj)
    if isinstance(obj, Mapping):
        return {str(k): _jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple, set, frozenset)):
        return [_jsonable(v) for v in obj]
    return str(obj)


def _print_json(obj: Any) -> None:
    _out(json.dumps(_jsonable(obj), indent=2, allow_nan=False, ensure_ascii=False))


def _pct(x: float | None, digits: int = 1) -> str:
    return "n/a" if x is None or not math.isfinite(x) else f"{100 * x:.{digits}f}%"


def _est(e: Estimate | None) -> str:
    if e is None or e.value is None:
        return "n/a"
    if e.lo is None or e.hi is None:
        return _pct(e.value)
    return f"{_pct(e.value)} [{_pct(e.lo)}, {_pct(e.hi)}]"


def _usd(x: float | None) -> str:
    if x is None or not math.isfinite(x):
        return "n/a"
    return f"${x:.6f}" if abs(x) < 0.01 else f"${x:.4f}"


def _thr1(v: float) -> str:
    if v <= 0:
        return "0 (never escalate)"
    if v > 1:
        return f"{v:g} (always escalate)"
    return f"{v:.3g}"


def _thr(t: Sequence[float]) -> str:
    return ", ".join(_thr1(v) for v in t) or "-"


def _setup_console() -> None:
    """Never crash on characters the console encoding cannot represent (e.g. cp1252/cp437)."""
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is None:
            continue
        with contextlib.suppress(ValueError, OSError):  # detached or exotic streams
            reconfigure(errors="replace")


class _StderrHandler(logging.StreamHandler):  # type: ignore[type-arg]
    """Writes to whatever ``sys.stderr`` is at emit time (works under capture/redirects)."""

    def __init__(self) -> None:
        super().__init__(sys.stderr)

    @property  # type: ignore[override]
    def stream(self) -> Any:
        return sys.stderr

    @stream.setter
    def stream(self, value: Any) -> None:
        pass


def _setup_logging(verbosity: int) -> None:
    logger = logging.getLogger("shadowgate")
    for h in list(logger.handlers):
        if isinstance(h, _StderrHandler):
            logger.removeHandler(h)
    handler = _StderrHandler()
    handler.setFormatter(logging.Formatter("shadowgate: %(levelname)s: %(message)s"))
    logger.addHandler(handler)
    debug = os.environ.get("SHADOWGATE_DEBUG") == "1"
    if verbosity >= 2 or debug:
        logger.setLevel(logging.DEBUG)
    elif verbosity == 1:
        logger.setLevel(logging.INFO)
    else:
        logger.setLevel(logging.WARNING)
    logger.propagate = False


# --------------------------------------------------------------------------- ledger helpers


def _open_ledger(path: str | Path, *, create: bool = False) -> Ledger:
    from .ledger import Ledger

    p = Path(path)
    if not create and not p.is_file():
        raise UsageError(
            f"no ledger at {p} (run `shadowgate run` or `shadowgate demo` first, "
            "or point --ledger at an existing ledger)"
        )
    return Ledger(p)


def _resolve_run(ledger: Ledger, run_id: str | None, *, mode: str | None = None) -> str:
    """The requested run id (validated), or the latest run (of ``mode`` if given)."""
    runs = ledger.runs()
    if not runs:
        raise UsageError(f"ledger {ledger.path} has no runs yet")
    if run_id is not None:
        if not any(r.run_id == run_id for r in runs):
            known = ", ".join(r.run_id for r in runs[-5:])
            raise UsageError(f"no run {run_id!r} in ledger {ledger.path} (recent: {known})")
        return run_id
    if mode is not None:
        matching = [r for r in runs if r.mode == mode]
        if not matching:
            raise UsageError(
                f"ledger {ledger.path} has no {mode}-mode run; create one with "
                f"`shadowgate run ... --mode {mode}` or pass --run-id"
            )
        return matching[-1].run_id
    return runs[-1].run_id


def _run_tolerance(ledger: Ledger, run_id: str) -> float | None:
    """``audit.tolerance`` from the config snapshot stored with the run, if any."""
    for r in ledger.runs():
        if r.run_id == run_id:
            audit = r.config.get("audit") if isinstance(r.config, Mapping) else None
            tol = audit.get("tolerance") if isinstance(audit, Mapping) else None
            if isinstance(tol, (int, float)) and not isinstance(tol, bool):
                return float(tol)
    return None


def _summarize(decisions: Sequence[Decision], tolerance: float | None) -> AuditSummary:
    from .audit import summarize

    try:
        return summarize(decisions, tolerance=tolerance)
    except ValueError as exc:
        raise UsageError(str(exc)) from exc


def _sweep(decisions: Sequence[Decision], **kwargs: Any) -> SweepResult:
    from .sweep import sweep

    try:
        return sweep(decisions, **kwargs)
    except ValueError as exc:
        raise UsageError(str(exc)) from exc


def _report_module() -> Any:
    try:
        from . import report
    except ImportError as exc:  # pragma: no cover - only while the module is missing
        raise ShadowgateError(f"report rendering is unavailable: {exc}") from exc
    return report


# --------------------------------------------------------------------------- progress


class _Progress:
    """Single updating line on a TTY; plain periodic lines otherwise. Writes to stderr.

    Redraws are throttled (TTY: at most every ``TTY_INTERVAL_S`` plus the final line; otherwise
    one line per 10% of tasks) so console output never dominates the run time.
    """

    TTY_INTERVAL_S = 0.15

    def __init__(self, label: str, *, enabled: bool = True) -> None:
        self.label = label
        self.enabled = enabled
        self.tty = enabled and bool(getattr(sys.stderr, "isatty", lambda: False)())
        self._width = 0
        self._last_pct = -1
        self._last_draw = -math.inf

    def __call__(self, stats: RunStats, _d: Decision) -> None:
        if not self.enabled:
            return
        done = stats.completed + stats.skipped_existing
        if self.tty and done < stats.total:
            now = time.monotonic()
            if now - self._last_draw < self.TTY_INTERVAL_S:
                return
            self._last_draw = now
        elif not self.tty and done < stats.total:
            if (100 * done // max(stats.total, 1)) // 10 <= self._last_pct:
                return
        total = max(stats.total, 1)
        line = (
            f"{self.label}: {done}/{stats.total} ({100 * done // total}%)  "
            f"{stats.escalated} escalated  {stats.audited} audited  "
            f"{stats.failed} failed  ${stats.cost_total:.4f}  {stats.elapsed_s:.0f}s"
        )
        if self.tty:
            pad = max(0, self._width - len(line))
            sys.stderr.write("\r" + line + " " * pad)
            sys.stderr.flush()
            self._width = len(line)
        else:
            pct = 100 * done // total
            step = pct // 10
            if step > self._last_pct or done == stats.total:
                self._last_pct = step
                sys.stderr.write(line + "\n")
                sys.stderr.flush()

    def close(self) -> None:
        if self.enabled and self.tty and self._width:
            sys.stderr.write("\n")
            sys.stderr.flush()


def _stop_exit_code(stopped: str | None) -> int:
    return {
        None: EXIT_OK,
        "budget": EXIT_BUDGET,
        "failures": EXIT_RUNTIME,
        "interrupted": EXIT_INTERRUPTED,
    }.get(stopped, EXIT_RUNTIME)


# --------------------------------------------------------------------------- init


def _cmd_init(args: argparse.Namespace) -> int:
    from .datasets import arithmetic, save_tasks

    target = Path(args.dir)
    config_path = target / "shadowgate.toml"
    tasks_path = target / "tasks.jsonl"
    existing = [p for p in (config_path, tasks_path) if p.exists()]
    if existing and not args.force:
        names = ", ".join(str(p) for p in existing)
        raise UsageError(f"refusing to overwrite {names} (pass --force to replace)")
    target.mkdir(parents=True, exist_ok=True)
    config_path.write_text(STARTER_CONFIG, encoding="utf-8", newline="\n")
    save_tasks(arithmetic(20, seed=0), tasks_path)
    _out(f"wrote {config_path}")
    _out(f"wrote {tasks_path} (20 arithmetic tasks)")
    _out("")
    _out("next:")
    _out(f"  shadowgate run -c {config_path} -t {tasks_path}")
    _out("  shadowgate audit")
    return EXIT_OK


# --------------------------------------------------------------------------- demo


def _demo_config(seed: int) -> Config:
    from .config import parse_config

    raw = tomllib.loads(DEMO_CONFIG)
    raw["run"]["seed"] = seed
    return parse_config(raw)


def _cmd_demo(args: argparse.Namespace) -> int:
    from .datasets import arithmetic, save_tasks
    from .runner import run

    if args.n < 1:
        raise UsageError("--n must be >= 1")
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    tasks = arithmetic(args.n, seed=args.seed)
    save_tasks(tasks, out / "tasks.jsonl")
    (out / "shadowgate.toml").write_text(
        DEMO_CONFIG.replace("seed = 0\n", f"seed = {args.seed}\n", 1),
        encoding="utf-8",
        newline="\n",
    )
    cfg = _demo_config(args.seed)
    cascade, settings = cfg.build(tasks=tasks)
    raw_tiers = cfg.raw["tiers"]
    backends = cfg.raw["backends"]
    _out(
        f"shadowgate demo: {len(tasks)} simulated arithmetic tasks (seed {args.seed}); "
        f"fast tier skill {backends['fast']['skill']:g} (overconfident), "
        f"slow tier skill {backends['slow']['skill']:g}"
    )
    ledger_path = out / "ledger.sqlite"
    base = f"demo-n{args.n}-s{args.seed}"
    eval_id, serve_id = f"{base}-eval", f"{base}-serve"
    snapshot = cfg.snapshot()
    with _open_ledger(ledger_path, create=True) as ledger:
        results: dict[str, RunStats] = {}
        for run_id, mode in ((eval_id, "eval"), (serve_id, "serve")):
            progress = _Progress(f"{mode} run", enabled=not args.quiet)
            try:
                stats = run(
                    cascade,
                    tasks,
                    ledger,
                    run_id=run_id,
                    mode=mode,
                    workers=settings.workers,
                    config_snapshot=snapshot,
                    progress=progress,
                )
            finally:
                progress.close()
            results[mode] = stats
            _out(f"  {mode:<5} run {run_id}: {stats.summary_line()}")
            if stats.stopped:
                return _stop_exit_code(stats.stopped)
        serve_decisions = list(ledger.decisions(serve_id))
        summary = _summarize(serve_decisions, settings.tolerance)
        sweep_result = _sweep(list(ledger.decisions(eval_id)), seed=args.seed)

    _out("")
    _print_demo_summary(summary, sweep_result, float(raw_tiers[0]["threshold"]))
    _out("")
    _out(_demo_conclusion(summary, serve_decisions, raw_tiers[0]["name"]))
    report = _report_module()
    html_path = report.write_report(out / "report.html", summary, sweep_result)
    md_path = report.write_report(out / "report.md", summary, sweep_result)
    _out("")
    _out(f"report: {html_path} (also {md_path.name})")
    _out(f"explore: shadowgate audit --ledger {ledger_path} --run-id {serve_id}")
    _out(f"         shadowgate sweep --ledger {ledger_path} --run-id {eval_id}")
    _out(f"next:    shadowgate calibrate --ledger {ledger_path} --run-id {eval_id}")
    if args.open:
        import webbrowser

        webbrowser.open(Path(html_path).resolve().as_uri())
    return EXIT_OK


def _demo_conclusion(summary: AuditSummary, decisions: Sequence[Decision], tier: str) -> str:
    """One plain sentence: reported confidence on kept answers vs the audited disagreement."""
    kept = [
        float(d.attempts[0].confidence.score)
        for d in decisions
        if d.error is None
        and not d.escalated
        and d.attempts
        and d.attempts[0].confidence is not None
        and d.attempts[0].confidence.score is not None
    ]
    ref = summary.reference_tier or "the final tier"
    dis = summary.disagreement
    if not kept or dis is None or dis.value is None:
        return f"The {tier} tier kept no audited answers, so there is nothing to compare yet."
    conf = sum(kept) / len(kept)
    ci = ""
    if dis.lo is not None and dis.hi is not None:
        ci = f" ({100 * summary.level:.0f}% CI {100 * dis.lo:.0f}-{100 * dis.hi:.0f}%)"
    text = (
        f"The {tier} tier reports {100 * conf:.0f}% mean confidence on the answers it keeps; "
        f"the audit estimates {100 * dis.value:.0f}% of them disagree with the {ref} tier{ci}"
    )
    implied = 1.0 - conf
    if dis.lo is not None and dis.lo > implied:
        text += f", more than the {100 * implied:.0f}% its confidence implies"
    elif dis.value > implied:
        text += (
            f", more than the {100 * implied:.0f}% its confidence implies "
            "(though the interval includes it)"
        )
    return text + "."


def _print_demo_summary(summary: AuditSummary, sw: SweepResult, threshold: float) -> None:
    ref = summary.reference_tier or (summary.tiers[-1] if summary.tiers else "reference")
    _out(f"Serve mode: confidence threshold {threshold:.2f}, stratified shadow audits")
    _out(f"  escalation rate         {_est(summary.escalation_rate)}")
    _out(
        f"  kept by fast tier       {summary.n_skipped} decisions, "
        f"{summary.n_audited} shadow-audited by {ref!r}"
    )
    _out(f"  disagreement on kept    {_est(summary.disagreement)} (weighted by 1/pi)")
    if summary.skipped_error is not None:
        _out(f"  error on kept           {_est(summary.skipped_error)} (vs references)")
    if summary.served_accuracy is not None:
        _out(f"  served accuracy         {_est(summary.served_accuracy)}")
    _out(f"  cost per task           {_usd(summary.cost_per_task)}")
    if summary.est_savings is not None:
        _out(f"  est. savings vs {ref:<7} {_est(summary.est_savings)}")
    status = summary.status
    if summary.tolerance is not None:
        status += f" (tolerance {_pct(summary.tolerance)}"
        if summary.audits_to_resolve:
            status += f"; ~{summary.audits_to_resolve} more audits to resolve"
        status += ")"
    _out(f"  audit status            {status}")
    _out("")
    _out("Eval mode: every tier on every task, threshold sweep")
    for name, p in sw.baselines.items():
        _out(f"  {name:<22}  accuracy {_est(p.accuracy):<26} cost/task {_usd(p.cost_per_task)}")
    rec = sw.recommendation
    if rec is None:
        _out("  no recommendation: " + (sw.notes[-1] if sw.notes else "no point met the target"))
        return
    last = sw.baselines.get(f"only:{sw.tiers[-1]}")
    p = rec.holdout or rec.point
    where = f"held-out n={rec.n_holdout}" if rec.holdout is not None else "in-sample"
    line = (
        f"  recommended threshold   {_thr(rec.thresholds)} -> accuracy {_est(p.accuracy)}, "
        f"cost/task {_usd(p.cost_per_task)} ({where})"
    )
    _out(line)
    if rec.holdout is not None and "caution" in rec.note:
        _out("  (held-out accuracy is below the selection target; see the report's caveats)")
    if last is not None and last.cost_per_task and p.cost_per_task is not None:
        change = _pct(p.cost_per_task / last.cost_per_task - 1)
        _out(f"  cost vs {sw.tiers[-1] + '-only':<15} {change}")


# --------------------------------------------------------------------------- run


def _cmd_run(args: argparse.Namespace) -> int:
    from .config import load_config
    from .datasets import load_tasks
    from .runner import run

    if args.limit is not None and args.limit < 0:
        raise UsageError("--limit must be >= 0")
    if args.workers is not None and args.workers < 1:
        raise UsageError("--workers must be >= 1")
    if args.max_cost is not None and args.max_cost < 0:
        raise UsageError("--max-cost must be >= 0")
    cfg = load_config(args.config)
    tasks = load_tasks(args.tasks, limit=args.limit)
    if not tasks:
        raise DatasetError(f"{args.tasks}: no tasks")
    cascade, settings = cfg.build(tasks=tasks)
    ledger_path = Path(args.ledger) if args.ledger else settings.ledger_path
    workers = args.workers or settings.workers
    max_cost = args.max_cost if args.max_cost is not None else settings.max_cost_usd

    with _open_ledger(ledger_path, create=True) as ledger:
        existing = {r.run_id: r for r in ledger.runs()}
        if args.run_id:
            run_id = args.run_id
            prev = existing.get(run_id)
            if prev is not None and prev.mode != args.mode:
                raise UsageError(
                    f"run {run_id!r} exists in {ledger_path} with mode {prev.mode!r}; "
                    f"pass --mode {prev.mode} to resume it or choose another --run-id"
                )
        else:
            stamp = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
            base = f"{settings.name}-{args.mode}-{stamp}"
            run_id, k = base, 2
            while run_id in existing:  # never resume a run implicitly
                run_id, k = f"{base}-{k}", k + 1
        resuming = run_id in existing and not args.no_resume
        if not args.quiet:
            verb = "resuming" if resuming else "starting"
            _out(
                f"{verb} run {run_id}  (mode {args.mode}, {len(tasks)} tasks, "
                f"{workers} workers, ledger {ledger_path})"
            )
        progress = _Progress("run", enabled=not args.quiet)
        try:
            stats = run(
                cascade,
                tasks,
                ledger,
                run_id=run_id,
                mode=args.mode,
                workers=workers,
                max_cost_usd=max_cost,
                resume=not args.no_resume,
                config_snapshot=cfg.snapshot(),
                progress=progress,
            )
        finally:
            progress.close()
        pending = sum(1 for _ in ledger.pending_audits(run_id))

    _out(f"run {run_id}: {stats.summary_line()}")
    resume_cmd = f"shadowgate run -c {args.config} -t {args.tasks} --run-id {run_id}"
    if args.mode != "serve":
        resume_cmd += f" --mode {args.mode}"
    if args.ledger:
        resume_cmd += f" --ledger {args.ledger}"
    ledger_opt = f" --ledger {args.ledger}" if args.ledger else ""
    if stats.failed and not stats.stopped:
        _err(f"shadowgate: warning: {stats.failed} task(s) failed; see the ledger for details")
    if stats.stopped:
        reason = {
            "budget": f"spending cap of ${max_cost} reached",
            "failures": "too many consecutive failures",
            "interrupted": "interrupted",
        }.get(stats.stopped, stats.stopped)
        _err(f"shadowgate: stopped early ({reason}); resume with:")
        _err(f"  {resume_cmd}")
    elif not args.quiet:
        if pending:
            _out(
                f"{pending} deferred audit(s) pending: shadowgate audit --run-pending "
                f"-c {args.config} --run-id {run_id}{ledger_opt}"
            )
        nxt = "sweep" if args.mode == "eval" else "audit"
        _out(f"next: shadowgate {nxt} --run-id {run_id}{ledger_opt}")
    return _stop_exit_code(stats.stopped)


# --------------------------------------------------------------------------- audit


def _cmd_audit(args: argparse.Namespace) -> int:
    if args.run_pending:
        return _audit_run_pending(args)
    if args.config:
        raise UsageError("-c/--config is only used with --run-pending")
    ledger_path = Path(args.ledger) if args.ledger else DEFAULT_LEDGER
    with _open_ledger(ledger_path) as ledger:
        run_id = _resolve_run(ledger, args.run_id)
        tolerance = args.tolerance if args.tolerance is not None else _run_tolerance(ledger, run_id)
        summary = _summarize(list(ledger.decisions(run_id)), tolerance)
    return _emit_audit(args, summary)


def _emit_audit(args: argparse.Namespace, summary: AuditSummary) -> int:
    if args.json:
        _print_json(summary)
    else:
        _out(_report_module().render_text(summary).rstrip("\n"))
    if args.fail_on_breach and summary.status == "breach":
        _err(
            f"shadowgate: audit breach: skipped-case {summary.status_metric or 'error'} "
            f"exceeds tolerance {_pct(summary.tolerance)}"
        )
        return EXIT_BREACH
    return EXIT_OK


def _audit_run_pending(args: argparse.Namespace) -> int:
    from .config import load_config
    from .runner import run_pending_audits

    if not args.config:
        raise UsageError("--run-pending needs -c/--config to build the audit tier")
    cfg = load_config(args.config)
    ledger_path = Path(args.ledger) if args.ledger else cfg.settings.ledger_path
    with _open_ledger(ledger_path) as ledger:
        run_id = _resolve_run(ledger, args.run_id)
        decisions = list(ledger.decisions(run_id))
        # Simulated backends need the task list; the ledger stores every task.
        cascade, settings = cfg.build(tasks=[d.task for d in decisions])
        progress = _Progress("audits", enabled=not args.json)
        try:
            stats = run_pending_audits(
                cascade,
                ledger,
                run_id=run_id,
                workers=args.workers or settings.workers,
                max_cost_usd=args.max_cost if args.max_cost is not None else settings.max_cost_usd,
                progress=progress,
            )
        finally:
            progress.close()
        _err(f"pending audits for {run_id}: {stats.summary_line()}")
        tolerance = args.tolerance
        if tolerance is None:
            tolerance = settings.tolerance
        if tolerance is None:
            tolerance = _run_tolerance(ledger, run_id)
        summary = _summarize(list(ledger.decisions(run_id)), tolerance)
    code = _emit_audit(args, summary)
    if stats.stopped:
        return _stop_exit_code(stats.stopped)
    return code


# --------------------------------------------------------------------------- sweep


def _sweep_kwargs(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "objective": args.objective,
        "max_accuracy_drop": args.max_drop,
        "min_accuracy": args.min_accuracy,
        "budget_per_task": args.budget,
        "holdout": args.holdout,
        "seed": args.seed,
    }


def _point_line(name: str, p: OperatingPoint) -> str:
    return (
        f"  {name:<24} accuracy {_est(p.accuracy):<26} cost/task {_usd(p.cost_per_task):<11} "
        f"escalation {_pct(p.escalation_rate)}"
    )


def _render_sweep(sw: SweepResult) -> str:
    lines = [
        f"Threshold sweep: {sw.n} decisions, tiers {' -> '.join(sw.tiers)}, truth: {sw.truth}",
        f"  {len(sw.points)} operating points, {len(sw.frontier)} on the Pareto frontier",
        "",
        "Baselines",
    ]
    lines += [_point_line(name, p) for name, p in sw.baselines.items()]
    lines += ["", "Pareto frontier (cheapest first)"]
    frontier = [sw.points[i] for i in sw.frontier]
    if len(frontier) > 12:
        step = math.ceil(len(frontier) / 12)
        frontier = frontier[::step] + ([frontier[-1]] if (len(frontier) - 1) % step else [])
    lines += [_point_line(f"threshold {_thr(p.thresholds)}", p) for p in frontier]
    rec = sw.recommendation
    lines += ["", "Recommendation"]
    if rec is None:
        lines.append("  none: no operating point meets the objective")
    else:
        lines.append(f"  objective {rec.objective}: threshold {_thr(rec.thresholds)}")
        lines.append(_point_line(f"selection (n={rec.n_selection})", rec.point))
        if rec.holdout is not None:
            lines.append(_point_line(f"held-out (n={rec.n_holdout})", rec.holdout))
        if rec.delta_vs_best is not None and rec.best_single_tier:
            d = rec.delta_vs_best
            lines.append(
                f"  accuracy vs {rec.best_single_tier}-only: "
                f"{_signed_pts(d.value)} [{_signed_pts(d.lo)}, {_signed_pts(d.hi)}] points"
            )
        lines += textwrap.wrap(rec.note, 96, initial_indent="  ", subsequent_indent="  ")
    if sw.calibration:
        lines += ["", "Confidence calibration (non-final tiers)"]
        for tier, c in sw.calibration.items():
            lines.append(
                f"  {tier:<12} n={c.n}  ECE {_num(c.ece)}  Brier {_num(c.brier)}  "
                f"AUROC {_num(c.auroc)}  AURC {_num(c.aurc)}"
            )
    if sw.notes:
        lines += ["", "Notes"] + [f"  - {n}" for n in sw.notes]
    return "\n".join(lines)


def _signed_pts(x: float | None) -> str:
    return "n/a" if x is None else f"{100 * x:+.1f}"


def _num(x: float | None) -> str:
    return "n/a" if x is None or not math.isfinite(x) else f"{x:.3f}"


def _cmd_sweep(args: argparse.Namespace) -> int:
    ledger_path = Path(args.ledger) if args.ledger else DEFAULT_LEDGER
    with _open_ledger(ledger_path) as ledger:
        run_id = _resolve_run(ledger, args.run_id, mode="eval")
        sw = _sweep(list(ledger.decisions(run_id)), **_sweep_kwargs(args))
    if args.json:
        _print_json({"run_id": run_id, **_jsonable(sw)})
    else:
        _out(f"run {run_id}")
        _out(_render_sweep(sw))
    return EXIT_OK


# --------------------------------------------------------------------------- calibrate

_MIN_CALIBRATION_PAIRS = 10


def _interp(points: Sequence[tuple[float, float]], x: float) -> float:
    """Piecewise-linear map with clamping, as ``confidence.Calibrated.apply`` computes it."""
    if x <= points[0][0]:
        return points[0][1]
    if x >= points[-1][0]:
        return points[-1][1]
    lo = 0
    hi = len(points) - 1
    while hi - lo > 1:  # binary search for the segment containing x
        mid = (lo + hi) // 2
        if points[mid][0] <= x:
            lo = mid
        else:
            hi = mid
    (x0, y0), (x1, y1) = points[lo], points[hi]
    return y0 + (y1 - y0) * (x - x0) / (x1 - x0)


def _thin_knots(knots: Sequence[tuple[float, float]], k: int) -> list[tuple[float, float]]:
    """At most ``k`` knots: keep both ends, greedily drop the interior knot whose removal
    changes the interpolated curve least. A subset of a monotone knot list stays monotone."""
    pts = list(knots)
    k = max(2, k)
    while len(pts) > k:
        best_i, best_dev = 1, math.inf
        for i in range(1, len(pts) - 1):
            (x0, y0), (x1, y1), (x2, y2) = pts[i - 1], pts[i], pts[i + 1]
            dev = abs(y1 - (y0 + (y2 - y0) * (x1 - x0) / (x2 - x0)))
            if dev < best_dev:
                best_i, best_dev = i, dev
        del pts[best_i]
    return pts


def _round_knots(knots: Sequence[tuple[float, float]]) -> list[tuple[float, float]]:
    """Round to 4 d.p., merging knots whose x collide (rounding is monotone, so y stays sorted)."""
    out: list[tuple[float, float]] = []
    for x, y in knots:
        rx, ry = round(x, 4), min(1.0, max(0.0, round(y, 4)))
        if out and rx <= out[-1][0]:
            out[-1] = (out[-1][0], max(out[-1][1], ry))
        else:
            out.append((rx, ry))
    return out


def _fit_points(
    scores: Sequence[float], labels: Sequence[bool], k: int
) -> list[tuple[float, float]]:
    from .sweep import fit_isotonic

    return _round_knots(_thin_knots(fit_isotonic(scores, labels), k))


def _cal_metrics(scores: Sequence[float], labels: Sequence[bool]) -> dict[str, float | None]:
    from . import stats

    if not scores or not all(0.0 <= s <= 1.0 for s in scores):
        return {"ece": None, "brier": None}
    return {"ece": stats.ece(scores, labels), "brier": stats.brier(scores, labels)}


def _toml_value(v: Any) -> str:
    """Inline TOML for a JSON-like value (the config snapshot holds only such values)."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return json.dumps(v)  # JSON string escapes are valid TOML basic-string escapes
    if isinstance(v, Mapping):
        if not v:
            return "{}"
        items = ", ".join(f"{_toml_key(str(k))} = {_toml_value(x)}" for k, x in v.items())
        return "{ " + items + " }"
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_toml_value(x) for x in v) + "]"
    raise UsageError(f"cannot write {type(v).__name__} value {v!r} as TOML")


def _toml_key(k: str) -> str:
    bare = k and all(c.isalnum() or c in "-_" for c in k) and k.isascii()
    return k if bare else json.dumps(k)


def _tier_confidence_spec(ledger: Ledger, run_id: str, tier: str) -> Mapping[str, Any] | None:
    for r in ledger.runs():
        if r.run_id != run_id or not isinstance(r.config, Mapping):
            continue
        tiers = r.config.get("tiers")
        if not isinstance(tiers, list):
            return None
        for t in tiers:
            if isinstance(t, Mapping) and t.get("name") == tier:
                spec = t.get("confidence")
                return spec if isinstance(spec, Mapping) and spec.get("type") else None
    return None


def _calibration_pairs(
    decisions: Sequence[Decision], tier: str, truth: str
) -> tuple[list[float], list[bool], str, int, int]:
    """(scores, labels, resolved truth, n undecided, n attempts with a score)."""
    scored = []
    for d in decisions:
        for a in d.attempts:
            if a.tier != tier or a.error is not None or a.confidence is None:
                continue
            s = a.confidence.score
            if s is None or not math.isfinite(float(s)):
                continue
            scored.append((float(s), a))
    if truth == "auto":
        has_ref = bool(scored) and all(a.correct is not None for _, a in scored)
        truth = "reference" if has_ref else "audit-tier"
    scores: list[float] = []
    labels: list[bool] = []
    undecided = 0
    for s, a in scored:
        j = a.correct if truth == "reference" else a.agreement
        if j is None:
            continue
        if j.equivalent is None:
            undecided += 1
            continue
        scores.append(s)
        labels.append(bool(j.equivalent))
    return scores, labels, truth, undecided, len(scored)


def _cmd_calibrate(args: argparse.Namespace) -> int:
    import random

    from .audit import infer_tier_order

    if args.max_knots < 2:
        raise UsageError("--max-knots must be >= 2")
    ledger_path = Path(args.ledger) if args.ledger else DEFAULT_LEDGER
    with _open_ledger(ledger_path) as ledger:
        run_id = _resolve_run(ledger, args.run_id, mode="eval")
        decisions = list(ledger.decisions(run_id))
        mode = next((r.mode for r in ledger.runs() if r.run_id == run_id), "n/a")
        tiers, final = infer_tier_order(decisions)
        tier = args.tier or (tiers[0] if tiers else None)
        if tier is None or tier not in tiers:
            raise UsageError(f"run {run_id} has no tier {tier!r} (tiers: {', '.join(tiers)})")
        if tier == final or tier == tiers[-1]:
            raise UsageError(
                f"tier {tier!r} is the final tier of run {run_id}; it never escalates, so its "
                f"confidence is unused (calibrate one of: {', '.join(tiers[:-1])})"
            )
        base_spec = _tier_confidence_spec(ledger, run_id, tier)
    scores, labels, truth, undecided, n_scored = _calibration_pairs(decisions, tier, args.truth)
    if len(scores) < _MIN_CALIBRATION_PAIRS:
        what = "references" if truth == "reference" else "agreement with the final tier"
        hint = (
            "re-run the tasks with `shadowgate run ... --mode eval`, which runs every tier on "
            "every task and records correctness (tasks with references) and agreement"
        )
        raise UsageError(
            f"run {run_id} ({mode} mode) has {len(scores)} scored attempts of tier {tier!r} "
            f"labelled by {what} (need >= {_MIN_CALIBRATION_PAIRS}); {hint}"
        )
    notes: list[str] = []
    if mode == "serve" and truth == "audit-tier":
        notes.append(
            "labels come from sampled shadow audits of a serve-mode run, which are not a "
            "uniform sample of scores; an eval-mode run gives an unbiased fit"
        )
    if undecided:
        notes.append(f"{undecided} attempt(s) with an undecided judgement were left out")
    if truth == "audit-tier":
        notes.append("truth is agreement with the final tier, not correctness")

    points = _fit_points(scores, labels, args.max_knots)
    before = _cal_metrics(scores, labels)
    after = _cal_metrics([_interp(points, s) for s in scores], labels)
    # 2-fold cross-fitting: fit on one half, evaluate on the other, average the two halves.
    idx = list(range(len(scores)))
    random.Random(0).shuffle(idx)
    halves = (idx[: len(idx) // 2], idx[len(idx) // 2 :])
    cross: dict[str, list[float]] = {"ece": [], "brier": []}
    for fit_i, eval_i in (halves, halves[::-1]):
        pts = _fit_points([scores[i] for i in fit_i], [labels[i] for i in fit_i], args.max_knots)
        m = _cal_metrics([_interp(pts, scores[i]) for i in eval_i], [labels[i] for i in eval_i])
        for key in cross:
            v = m[key]
            if v is not None:
                cross[key].append(v)
    cross_fitted = {k: (sum(v) / len(v) if len(v) == 2 else None) for k, v in cross.items()}

    points_toml = "[" + ", ".join(f"[{x!r}, {y!r}]" for x, y in points) + "]"
    if base_spec is not None:
        base_toml = _toml_value(dict(base_spec))
        notes_snippet = ""
    else:
        base_toml = "<your current confidence spec>"
        notes_snippet = (
            "the run's stored config has no confidence spec for this tier; replace "
            "<your current confidence spec> with the tier's current `confidence` table"
        )
        notes.append(notes_snippet)
    snippet = (
        f'[[tiers]]  # replace the confidence line of tier "{tier}" with:\n'
        f'confidence = {{ type = "calibrated", base = {base_toml}, points = {points_toml} }}'
    )
    result = {
        "run_id": run_id,
        "mode": mode,
        "tier": tier,
        "truth": truth,
        "n": len(scores),
        "n_scored": n_scored,
        "n_undecided": undecided,
        "accuracy": sum(labels) / len(labels),
        "mean_confidence": sum(scores) / len(scores),
        "max_knots": args.max_knots,
        "points": [list(p) for p in points],
        "before": before,
        "after": after,
        "cross_fitted": cross_fitted,
        "base_spec": dict(base_spec) if base_spec is not None else None,
        "snippet": snippet,
        "notes": notes,
    }
    if args.json:
        _print_json(result)
        return EXIT_OK
    label = "correct" if truth == "reference" else "agreeing with the final tier"
    _out(f"run {run_id} ({mode}), tier {tier!r}: {len(scores)} (confidence, {label}) pairs")
    _out(
        f"  mean confidence {_pct(result['mean_confidence'])}, "
        f"observed {_pct(result['accuracy'])} {label}"
    )
    _out(f"  {'':<24} {'ECE':>7} {'Brier':>7}")
    rows = (
        ("before (raw scores)", before),
        ("after, in-sample", after),
        ("after, 2-fold cross-fit", cross_fitted),
    )
    for name, m in rows:
        _out(f"  {name:<24} {_num(m['ece']):>7} {_num(m['brier']):>7}")
    _out(f"  {len(points)} knots (max {args.max_knots}); in-sample numbers are optimistic,")
    _out("  the cross-fitted ECE is the honest estimate for new data")
    for n in notes:
        _out("  note: " + n)
    _out("")
    _out(snippet)
    _out("")
    _out("Thresholds then apply to the calibrated scale; re-run in eval mode and sweep to pick")
    _out("a new one.")
    return EXIT_OK


# --------------------------------------------------------------------------- report


def _cmd_report(args: argparse.Namespace) -> int:
    from .errors import InsufficientData

    ledger_path = Path(args.ledger) if args.ledger else DEFAULT_LEDGER
    with _open_ledger(ledger_path) as ledger:
        run_id = _resolve_run(ledger, args.run_id)
        decisions = list(ledger.decisions(run_id))
        tolerance = args.tolerance if args.tolerance is not None else _run_tolerance(ledger, run_id)
        summary = _summarize(decisions, tolerance)
        sweep_id = args.sweep_run_id
        if sweep_id is None and summary.mode == "eval":
            sweep_id = run_id
        sw = None
        if sweep_id is not None:
            sweep_id = _resolve_run(ledger, sweep_id)
            sweep_decisions = decisions if sweep_id == run_id else list(ledger.decisions(sweep_id))
            try:
                sw = _sweep(sweep_decisions)
            except InsufficientData as exc:
                if args.sweep_run_id is not None:
                    raise
                log.warning("report without a threshold sweep: %s", exc)
    try:
        path = _report_module().write_report(args.output, summary, sw)
    except ValueError as exc:
        raise UsageError(str(exc)) from exc
    extra = f" with sweep of {sweep_id}" if sw is not None else ""
    _out(f"wrote {path} (run {run_id}{extra})")
    return EXIT_OK


# --------------------------------------------------------------------------- runs / export


def _cmd_runs(args: argparse.Namespace) -> int:
    ledger_path = Path(args.ledger) if args.ledger else DEFAULT_LEDGER
    with _open_ledger(ledger_path) as ledger:
        runs = ledger.runs()
    if args.json:
        _print_json(runs)
        return EXIT_OK
    if not runs:
        _out(f"no runs in {ledger_path}")
        return EXIT_OK
    width = max(6, *(len(r.run_id) for r in runs))
    _out(f"{'run id':<{width}}  {'mode':<5}  {'decisions':>9}  created (UTC)")
    for r in runs:
        _out(f"{r.run_id:<{width}}  {r.mode:<5}  {r.n_decisions:>9}  {r.created_at[:19]}")
    return EXIT_OK


def _cmd_export(args: argparse.Namespace) -> int:
    ledger_path = Path(args.ledger) if args.ledger else DEFAULT_LEDGER
    with _open_ledger(ledger_path) as ledger:
        run_id = _resolve_run(ledger, args.run_id)
        n = ledger.export_jsonl(args.output, run_id)
    _out(f"wrote {n} decisions of run {run_id} to {args.output}")
    return EXIT_OK


# --------------------------------------------------------------------------- datasets


def _cmd_datasets_make(args: argparse.Namespace) -> int:
    from .datasets import make, save_tasks

    if args.n < 0:
        raise UsageError("-n must be >= 0")
    kwargs: dict[str, Any] = {"n": args.n, "seed": args.seed}
    if args.min_steps is not None:
        kwargs["min_steps"] = args.min_steps
    if args.max_steps is not None:
        kwargs["max_steps"] = args.max_steps
    tasks = make(args.name, **kwargs)
    save_tasks(tasks, args.output)
    _out(f"wrote {len(tasks)} {args.name} tasks to {args.output}")
    return EXIT_OK


def _cmd_datasets_show(args: argparse.Namespace) -> int:
    from .datasets import load_tasks

    tasks = load_tasks(args.tasks)
    n_ref = sum(1 for t in tasks if t.reference is not None)
    _out(f"{args.tasks}: {len(tasks)} tasks, {n_ref} with references")
    levels: dict[str, int] = {}
    for t in tasks:
        level = t.meta.get("level")
        if isinstance(level, str):
            levels[level] = levels.get(level, 0) + 1
    if levels:
        _out("levels: " + ", ".join(f"{k} {v}" for k, v in sorted(levels.items())))
    for t in tasks[: max(0, args.limit)]:
        _out("")
        meta = {k: t.meta[k] for k in ("level", "difficulty", "steps") if k in t.meta}
        meta_s = "  " + json.dumps(meta) if meta else ""
        _out(f"[{t.id}] reference: {t.reference if t.reference is not None else '-'}{meta_s}")
        prompt = t.prompt if len(t.prompt) <= 400 else t.prompt[:397] + "..."
        _out(prompt)
    return EXIT_OK


# --------------------------------------------------------------------------- parser


class _Formatter(argparse.RawDescriptionHelpFormatter):
    def __init__(self, prog: str) -> None:
        super().__init__(prog, max_help_position=30)


def _exit_code_text() -> str:
    return "exit codes:\n" + "\n".join(f"  {k:<4} {v}" for k, v in EXIT_CODES.items())


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="shadowgate",
        formatter_class=_Formatter,
        description=(
            "Confidence-gated model cascades that audit the cases they skip.\n"
            "A cheap tier answers first; a confidence estimator decides whether to escalate;\n"
            "shadow audits estimate how often the kept answers are wrong."
        ),
        epilog=(
            "examples:\n"
            "  shadowgate demo                               offline end-to-end demo + report\n"
            "  shadowgate init my-project                    starter config and tasks\n"
            "  shadowgate run -c shadowgate.toml -t tasks.jsonl\n"
            "  shadowgate audit --tolerance 0.05 --fail-on-breach\n"
            "  shadowgate run -c shadowgate.toml -t tasks.jsonl --mode eval\n"
            "  shadowgate sweep --objective max-savings --max-drop 0.01\n"
            "  shadowgate calibrate --tier fast              isotonic confidence map + snippet\n"
            "  shadowgate report -o report.html\n\n" + _exit_code_text() + "\n\n"
            "Set SHADOWGATE_DEBUG=1 to show tracebacks."
        ),
    )
    parser.add_argument("--version", action="version", version=f"shadowgate {__version__}")
    parser.add_argument(
        "-v", "--verbose", action="count", default=0, help="more logging (-vv for debug)"
    )
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")
    sub.required = True

    def add(name: str, help_: str, epilog: str, func: Callable[[argparse.Namespace], int]) -> Any:
        p = sub.add_parser(
            name, help=help_, description=help_, epilog=epilog, formatter_class=_Formatter
        )
        p.set_defaults(func=func)
        return p

    def ledger_opt(p: argparse.ArgumentParser, default: str = str(DEFAULT_LEDGER)) -> None:
        p.add_argument(
            "--ledger", metavar="PATH", default=None, help=f"ledger file (default: {default})"
        )

    def run_id_opt(p: argparse.ArgumentParser, what: str = "the latest run") -> None:
        p.add_argument("--run-id", metavar="ID", default=None, help=f"run to use (default: {what})")

    # init
    p = add(
        "init",
        "write a starter config (shadowgate.toml) and 20 example tasks (tasks.jsonl)",
        "examples:\n  shadowgate init\n  shadowgate init my-cascade --force",
        _cmd_init,
    )
    p.add_argument("dir", nargs="?", default=".", metavar="DIR", help="target directory")
    p.add_argument("--force", action="store_true", help="overwrite existing files")

    # demo
    p = add(
        "demo",
        "fully offline end-to-end demo: simulated models, eval + serve runs, HTML report",
        "examples:\n  shadowgate demo\n  shadowgate demo --n 1000 --seed 3 --out demo --open",
        _cmd_demo,
    )
    p.add_argument("--out", metavar="DIR", default="shadowgate-demo", help="output directory")
    p.add_argument("--n", type=int, default=400, metavar="N", help="number of tasks (400)")
    p.add_argument("--seed", type=int, default=0, metavar="S", help="dataset and model seed (0)")
    p.add_argument("--open", action="store_true", help="open the HTML report in a browser")
    p.add_argument("-q", "--quiet", action="store_true", help="no progress output")

    # run
    p = add(
        "run",
        "route tasks through the cascade and record every decision in the ledger",
        "examples:\n"
        "  shadowgate run -c shadowgate.toml -t tasks.jsonl\n"
        "  shadowgate run -c shadowgate.toml -t tasks.jsonl --mode eval --limit 200\n"
        "  shadowgate run -c shadowgate.toml -t tasks.jsonl --run-id nightly --max-cost 5\n\n"
        "Runs are resumable: re-run with the same --run-id to skip tasks already recorded.\n\n"
        + _exit_code_text(),
        _cmd_run,
    )
    p.add_argument("-c", "--config", required=True, metavar="CONFIG", help="TOML config")
    p.add_argument("-t", "--tasks", required=True, metavar="TASKS", help=".jsonl/.json/.csv")
    ledger_opt(p, "run.ledger from the config, else .shadowgate/ledger.sqlite")
    p.add_argument(
        "--run-id",
        metavar="ID",
        default=None,
        help="run id; reuse one to resume (default: <run.name>-<mode>-<timestamp>)",
    )
    p.add_argument("--mode", choices=("serve", "eval"), default="serve", help="serve (default)")
    p.add_argument("--limit", type=int, default=None, metavar="N", help="first N tasks only")
    p.add_argument("--workers", type=int, default=None, metavar="N", help="tasks in flight")
    p.add_argument("--max-cost", type=float, default=None, metavar="USD", help="spending cap")
    p.add_argument("--no-resume", action="store_true", help="re-route tasks already recorded")
    p.add_argument("-q", "--quiet", action="store_true", help="only print the final summary")

    # audit
    p = add(
        "audit",
        "summarise the shadow audit of a run: how often are kept (skipped) answers wrong?",
        "examples:\n"
        "  shadowgate audit\n"
        "  shadowgate audit --run-id nightly --tolerance 0.02 --fail-on-breach\n"
        "  shadowgate audit --run-pending -c shadowgate.toml     # complete deferred audits\n"
        "  shadowgate audit --json > audit.json\n\n" + _exit_code_text(),
        _cmd_audit,
    )
    ledger_opt(p)
    run_id_opt(p)
    p.add_argument(
        "--tolerance",
        type=float,
        default=None,
        metavar="T",
        help="acceptable skipped-case error/disagreement (default: audit.tolerance of the run)",
    )
    p.add_argument("--json", action="store_true", help="machine-readable output")
    p.add_argument("--fail-on-breach", action="store_true", help="exit 3 if status is breach")
    p.add_argument("--run-pending", action="store_true", help="first run pending deferred audits")
    p.add_argument("-c", "--config", metavar="CONFIG", default=None, help="for --run-pending")
    p.add_argument("--workers", type=int, default=None, metavar="N", help="for --run-pending")
    p.add_argument("--max-cost", type=float, default=None, metavar="USD", help="for --run-pending")

    # sweep
    p = add(
        "sweep",
        "sweep confidence thresholds over an eval-mode run and recommend one",
        "examples:\n"
        "  shadowgate sweep\n"
        "  shadowgate sweep --objective min-accuracy --min-accuracy 0.95\n"
        "  shadowgate sweep --objective max-accuracy --budget 0.002 --json\n\n"
        "objectives:\n"
        "  max-savings   cheapest point within --max-drop of the best single tier's accuracy\n"
        "  max-accuracy  most accurate point with cost/task <= --budget\n"
        "  min-accuracy  cheapest point with accuracy >= --min-accuracy",
        _cmd_sweep,
    )
    ledger_opt(p)
    run_id_opt(p, "the latest eval-mode run")
    p.add_argument(
        "--objective",
        choices=("max-savings", "max-accuracy", "min-accuracy"),
        default="max-savings",
        help="selection objective (max-savings)",
    )
    p.add_argument("--max-drop", type=float, default=0.01, metavar="X", help="(0.01)")
    p.add_argument("--min-accuracy", type=float, default=None, metavar="X")
    p.add_argument("--budget", type=float, default=None, metavar="X", help="USD per task")
    p.add_argument("--holdout", type=float, default=0.3, metavar="F", help="held-out share (0.3)")
    p.add_argument("--seed", type=int, default=0, metavar="S", help="split seed (0)")
    p.add_argument("--json", action="store_true", help="machine-readable output")

    # calibrate
    p = add(
        "calibrate",
        "fit an isotonic calibration map for a tier's confidence and print a config snippet",
        "examples:\n"
        "  shadowgate calibrate\n"
        "  shadowgate calibrate --run-id nightly-eval --tier fast --max-knots 12\n"
        "  shadowgate calibrate --truth audit-tier --json\n\n"
        "Uses (confidence, correct) pairs of one non-final tier, from an eval-mode run (every\n"
        "tier answers every task). Prints ECE/Brier before and after (in-sample and 2-fold\n"
        'cross-fitted) and a `confidence = { type = "calibrated", ... }` line for the config.\n'
        "truth: reference (vs task references), audit-tier (agreement with the final tier),\n"
        "auto (reference when every scored attempt is graded).",
        _cmd_calibrate,
    )
    ledger_opt(p)
    run_id_opt(p, "the latest eval-mode run")
    p.add_argument("--tier", metavar="NAME", default=None, help="tier to calibrate (first tier)")
    p.add_argument(
        "--truth", choices=("auto", "reference", "audit-tier"), default="auto", help="(auto)"
    )
    p.add_argument("--max-knots", type=int, default=20, metavar="K", help="knot limit (20)")
    p.add_argument("--json", action="store_true", help="machine-readable output")

    # report
    p = add(
        "report",
        "write an HTML or Markdown report (format from the -o suffix)",
        "examples:\n"
        "  shadowgate report -o report.html\n"
        "  shadowgate report --run-id nightly --sweep-run-id calib-eval -o report.md\n\n"
        "An eval-mode run includes its own threshold sweep; --sweep-run-id adds the sweep of\n"
        "an eval-mode run to the report of a serve-mode run.",
        _cmd_report,
    )
    ledger_opt(p)
    run_id_opt(p)
    p.add_argument("--sweep-run-id", metavar="ID", default=None, help="eval run to sweep")
    p.add_argument("-o", "--output", required=True, metavar="OUT", help=".html or .md")
    p.add_argument("--tolerance", type=float, default=None, metavar="T")

    # runs
    p = add("runs", "list the runs in a ledger", "examples:\n  shadowgate runs --json", _cmd_runs)
    ledger_opt(p)
    p.add_argument("--json", action="store_true", help="machine-readable output")

    # export
    p = add(
        "export",
        "export a run's decisions as JSONL (one decision per line)",
        "examples:\n  shadowgate export -o decisions.jsonl\n"
        "  shadowgate export --run-id nightly -o nightly.jsonl",
        _cmd_export,
    )
    ledger_opt(p)
    run_id_opt(p)
    p.add_argument("-o", "--output", required=True, metavar="OUT.jsonl")

    # datasets
    p = sub.add_parser(
        "datasets",
        help="generate or inspect task files",
        description="generate or inspect task files",
        formatter_class=_Formatter,
    )
    dsub = p.add_subparsers(dest="datasets_command", metavar="ACTION")
    dsub.required = True
    q = dsub.add_parser(
        "make",
        help="generate a built-in synthetic dataset",
        description="generate a built-in synthetic dataset",
        epilog="examples:\n  shadowgate datasets make arithmetic -n 500 -o tasks.jsonl\n"
        "  shadowgate datasets make arithmetic -n 100 --min-steps 4 -o hard.jsonl",
        formatter_class=_Formatter,
    )
    q.set_defaults(func=_cmd_datasets_make)
    q.add_argument("name", metavar="NAME", help="generator (arithmetic)")
    q.add_argument("-n", type=int, required=True, metavar="N", help="number of tasks")
    q.add_argument("--seed", type=int, default=0, metavar="S")
    q.add_argument("-o", "--output", required=True, metavar="OUT.jsonl")
    q.add_argument("--min-steps", type=int, default=None, metavar="K")
    q.add_argument("--max-steps", type=int, default=None, metavar="K")
    q = dsub.add_parser(
        "show",
        help="summarise a task file and print a few tasks",
        description="summarise a task file and print a few tasks",
        epilog="examples:\n  shadowgate datasets show tasks.jsonl --limit 5",
        formatter_class=_Formatter,
    )
    q.set_defaults(func=_cmd_datasets_show)
    q.add_argument("tasks", metavar="TASKS")
    q.add_argument("--limit", type=int, default=3, metavar="N", help="tasks to print (3)")
    return parser


# --------------------------------------------------------------------------- main


def _error_code(exc: ShadowgateError) -> int:
    # A missing ledger or unknown run is a UsageError; other LedgerErrors are runtime errors.
    if isinstance(exc, (UsageError, ConfigError, DatasetError)):
        return EXIT_USAGE
    return EXIT_RUNTIME


def main(argv: Sequence[str] | None = None) -> int:
    """Run the CLI; returns the process exit code (see :data:`EXIT_CODES`)."""
    _setup_console()
    parser = build_parser()
    try:
        args = parser.parse_args(list(argv) if argv is not None else None)
    except SystemExit as exc:  # --help, --version, usage errors
        code = exc.code
        return code if isinstance(code, int) else (0 if code is None else EXIT_USAGE)
    _setup_logging(args.verbose)
    debug = os.environ.get("SHADOWGATE_DEBUG") == "1"
    try:
        return int(args.func(args))
    except KeyboardInterrupt:
        _err("shadowgate: interrupted")
        return EXIT_INTERRUPTED
    except ShadowgateError as exc:
        if debug:
            traceback.print_exc()
        _err(f"shadowgate: error: {exc}")
        return _error_code(exc)
    except OSError as exc:
        if debug:
            traceback.print_exc()
        _err(f"shadowgate: error: {exc}")
        return EXIT_RUNTIME
    except Exception as exc:
        if debug:
            traceback.print_exc()
        _err(f"shadowgate: error: unexpected {type(exc).__name__}: {exc}")
        _err("shadowgate: set SHADOWGATE_DEBUG=1 for a traceback")
        return EXIT_RUNTIME
    finally:
        sys.stdout.flush()


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
